config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  root :to => 'home#index'

  resources :users
  resources :games do
    resources :comments
  end

  post '/login' => 'sessions#login'
  delete '/logout' => 'sessions#logout'

  post '/addscore' => 'games#addscore'

  post '/diplay_img' => 'images#displayimg'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
    validates :title, :presence => true,
                    :length => { :minimum => 5 }
end

app/models/image.rb
class Image < ActiveRecord::Base
  def img=(input_data)
    self.filename = input_data.original_filename
    self.filetype = input_data.content_type.chomp
    self.img = input_data.read
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :games
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:current_user_id]) if session[:current_user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/' unless @current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end


  def edit
  end

  def destroy
    puts 'inside destroy'
    @game = Game.find(params[:game_id])
    puts 'the game is'
    puts @game
    @comment = @game.comments.find(params[:id])
    puts 'the comment about to be destroy is '
    puts @comment
    @comment.destroy
    redirect_to game_path(@game)
  end

  def create
    puts 'params are '
    puts params
    puts 'commenter is '
    puts params[:comment]
    puts params[:comment][:body]
    @game = Game.find(params[:game_id])
    @comment = Comment.new({commenter: params[:comment][:commenter], body: params[:comment][:body], game_id: @game.id})
    if @comment.save!
      puts "comment is "
      puts @comment.body
      puts @comment.commenter
      flash[:notice] = "Comment saved"
    else
      flash[:notice] = "A problem has occurred. Your comment couldn't be posted."
    end
    return redirect_to game_path(@game)
  end

end

  private

    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    # if session[:current_user_id]
    #   @logged_user = User.find(session[:current_user_id])
    # end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    puts 'now the game is'
    puts @game
    puts 'coords are '
    puts @game.coordinates
    @coords = @game.coordinates.split(',')
    puts 'each coord is '
    puts @coords[0]
    puts @coords[1]

    if @game.user_id != nil
      @user_game = User.find(@game.user_id)
      puts 'the user obj in relation is '
      puts @user_game
    else
      puts "No user_id found"
    end
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.create(game_params)
    puts 'game params are'
    puts game_params
    puts 'full game obj is'
    puts @game

    respond_to do |format|
      if @game.save
        puts 'game has been saved to db, about to redirect to game show'
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        # format.js
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
      # redirect_to games_path
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def addscore
    puts 'inside addscore, score params is '
    puts params[:score]
    puts 'original url is'
    url_id = request.referrer.split('/')[-1]
    puts url_id
    current_game = Game.find(url_id)
    puts 'current game is '
    puts current_game
    new_score = params[:score]
    current_game.update_attributes(:score => new_score)
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :description, :score, :coordinates)
    end

    def score_params
      params.require(:game).permit(:score)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@users = User.all
  	puts 'session id is'
  	puts session.id
  	#@user = User.find()
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def display_img
    @img = Image.find(params[:id])
    send_data(@img.img, :type => @img.filetype, :filename => @img.filename,
              :disposition => 'inline')
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery

  def login
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:current_user_id] = @user.id
      puts "successfully logged in"
      puts session[:current_user_id]
      redirect_to root_path({usr: @user, sesh: session[:current_user_id]})
    else
      flash[:alert] = "You did not log in"
      redirect_to '/'
    end
  end


  def logout
    puts 'about to log out'
    session.delete(session.id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
  protect_from_forgery

  def index
    @users = User.all
    puts 'current user is'
    puts :current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    end
  end

  def show
    @user = User.find_by(id: session[:user_id])
    puts 'entering user show page, u user is '
    puts @user
  end

  private

  def user_params
    params.require(:user).permit(:email, :age, :password, :password_confirmation, :first_name, :last_name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/index.html.erb
<div class="wrapper">

<div ng-include="'navbar.html'"></div>

<div class="main-view-container" ui-view></div>

<div ng-include="'footer.html'"></div>

</div>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_startgame.html.erb
  <div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">x</span>
    <p>

      <div class="main-content">
      <div class="location-question">
        <h1>Time for a Game</h1>
        Where are you located? <br>
        <form action="#">
        <input type="text" class="location-input" class="current-location" name="current-location" ng-model="desiredLoc"><br>
        <input class="submit-location" type="submit" value="Submit my Location" ng-click="startModal(2) "><br>
      </form>
        </div>
      </div>

    </p>
  </div>


<div id="mySecondModal" class="modal second-modal">

  <div class="modal-content">
    <span class="secondClose">x</span>
    <p>

      <div class="main-content">
      <div class="">
        <h1>GAME REQUEST</h1>
        Game title:  <br>
        Game location:  <br>
        Player 1:  <br>
        Player 2:  <br>
        Location: {{ desiredLoc}} <br>
        <form method="POST" action="/games">
          <input type="text" class="" class="current-location" name="current-location" ng-model="desiredLoc"><br>
          <input class="submit-location" type="submit" value="Create Game Request"><br>
        </form>
        </div>
      </div>

    </p>
  </div>

</div>

app/views/games/edit.html.erb
<div class="content-container">

<h1>Edit Your Game Info</h1>

<div class="edit-form">
	<%= render 'form' %>

	<%= link_to 'Show', @game %> |
	<%= link_to 'Back', games_path %>
</div>

</div>

app/views/games/index.html.erb
<div class="content-container" ng-app="myApp" ng-controller="MainCtrl" ng-init="lower = true">

<div class="waiting"><h2> They are waiting on you! </h2></div>

<div class="cannot-find">Can't find a game in your area? </div>
  <div class="other-linx-wrapper">
    <span class="other-linx-btn"><a href="#" ng-click="reloadRoute('games/new')">Start a game</a></span>
    <span class="other-linx-btn return-home"><a href="#" ng-click="reloadRoute('/')">Return Home</a></span>
  </div>  

<div class="table-map">

<div class="table-responsive col-xs-12 col-sm-6 col-md-8">
  <table class="table">

    <tbody>
      <% @games.each do |game| %>
        <tr ng-click="reloadRoute('/games/<%=game.id %>')">
          <td><div class="game-title"><%=  game.title %> </div><br>
            <div class="game-description"><%= game.description %></div>
          </td>
            <td>by: <%= game.id %></td>
          <p>
            <td class="game-edit-delete"></td>
          </p>
        </tr>
      <% end %>
    </tbody>
  </table></div>

  <div id="map"></div>
</div> <!-- table-map -->

<br>

</div>

<script>
function initMap() {
  console.log("inside init map");
  var map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: -34.397, lng: 150.644},
    zoom: 6
  });
  var infoWindow = new google.maps.InfoWindow({map: map});

  // Try HTML5 geolocation.
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(position) {
      var pos = {
        lat: position.coords.latitude,
        lng: position.coords.longitude
      };

      infoWindow.setPosition(pos);
      infoWindow.setContent('Location found.');
      map.setCenter(pos);
    }, function() {
      handleLocationError(true, infoWindow, map.getCenter());
    });
  } else {
    // Browser doesn't support Geolocation
    handleLocationError(false, infoWindow, map.getCenter());
  }
}

function handleLocationError(browserHasGeolocation, infoWindow, pos) {
  infoWindow.setPosition(pos);
  infoWindow.setContent(browserHasGeolocation ?
                        'Error: The Geolocation service failed.' :
                        'Error: Your browser doesn\'t support geolocation.');
}
</script>

app/views/games/new.html.erb
<div class="gamereq-wrapper" ng-app="myApp" ng-controller="MainCtrl">
  <div class="gamereq">

    <h2>GAME REQUEST</h2>
      <!-- <form method="POST" action="/games" id="gamereq-form"> -->

      <div class="gamereq-labels">
        <div class="gamereq-label">Desired location:</div><br>
        <div class="gamereq-label">Player 1:</div><br>
        <div class="gamereq-label">Player 2: </div><br>
        <div class="gamereq-label">Game title:</div><br>
        <div class="gamereq-label">Description:</div><br>
      </div>
      
      <form style="float: left; margin-top: 9%; "name="someform" ng-submit="someform.$valid && createGame(someform)" novalidate>
      <div class="gamereq-inputs">
        <span style="margin-bottom: -30px;">
        <input type="text" class="coordz gamereq-input" name="game[coordinates]" ng-model="game.address" placeholder="street address"> 
        <input type="text" class="town-country gamereq-input" ng-model="game.townCountry" placeholder="city/state and country"> 
      </span>

        <input name="game[player_1]"/ ng-model="game.player_1" placeholder="player 1"><br>
        <input name="game[player_2]"/ ng-model="game.player_2" placeholder="player 2"><br>
        <!-- <input  placeholder="awaiting" /><br> -->
        <input type="text" class="gamereq-input" name="game[title]" ng-model="game.title" placeholder="game title"><br>
        <input type="text" class="gamereq-input gamereq-input-descr" name="game[description]" ng-model="game.description" placeholder="description"><br>
        <input class="btn-success" ng-click="createGame(game)" value="Create Game"/>
      </div>
    </form>

    <div class="previous-btn">
      <%= link_to 'Back', games_path %>
    </div>

  </div>
</div>

app/views/games/show.html.erb
<div class="user-show" styl="background: red">

  Hello, you are on the user show page. :D


</div>

app/views/home/index.html.erb
<div class="all-content">

  <div class="welcome-intro">

  </div>

  <div class="section-wrapper" ng-hide="openLocationReq == true">
    <div class="bubble">
      <div class="bubble-content">
        <ul>Here's how to play:
        <p>
          <li> Click on "Find a Game" to view the list of proposed games in your area.
          <li> Select the most inviting game and view details.
          <li> Select your top 3 from the list of available tennis courts in the area in game detail section.
          <li> Select a preferred time window.
          <li> Send an email/comment on the game's wall to inform the host. This will include your selected preferences.
          <li> Wait for host's approval. Time and location will be sent via email to both parties based on matching preferences.
          <li> Once the game has ended, each player should record the scores on the game's wall. <br>
            <input type="button" class="btn-success find-game-btn" value="Find a game" ng-click="reloadRoute('/games/new')">
        </p>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.7/angular-resource.min.js"></script>
  <title>Tennis Buddy</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "angular" %>
  <%= javascript_include_tag "app" %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="../../../favicon.ico?v=2" />
  <link href="../../../app/assets/stylesheets/bootstrap.css">
</head>
<body class="page-body" ng-app="myApp" ng-controller="MainCtrl">
  <main class="body-inner-wrap" >

  <nav class="navbar navbar-default navwrap navbar-fixed-top" ng-init="showProfile = false; showLogin = false; showSignup = false;">
  <div class="container-fluid">
    <div class="navbar-header">

        <a class="navbar-brand" ng-click="reloadRoute('/')">
          <%= image_tag("tb.png") %>
        </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li class="navlinx"><a href="#" ng-click="reloadRoute('/games/new')">Start a game</a></li>
        <li class="navlinx"><a href="#" ng-click="reloadRoute('/games')">Find a game</a></li>

          <li ng-if="<%= session.id != nil %>" class="navlinx"><a style="margin-top: 15px !important;" ng-click="navToggle('showLogin')" href="#">Login</a></li>
          <li ng-if="<%= session.id != nil %>" class="navlinx"><a style="margin-top: 15px !important;" ng-click="navToggle('showSignup')" href="#">Signup</a></li>

          <li ng-if="<%= session.id != nil %>" class="navlinx">
            <div class="logout-btn"><%= button_to 'Logout', logout_path, :method => :delete %></div></li>

          <li class="navlinx"><a ng-click="navToggle('showProfile')" href="#">My profile</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="login-box" ng-if="tabArray.showLogin == true">

  <form action="/login" method="post">
    <p style="font-size: 25px">Log In</p>
    <hr>
    <p class="labels"><input type="text" name="email" placeholder="email"></input></p>
    <p class="labels"><input type="password" name="password" placeholder="password"></input></p>
    <button class="btn-success" ng-click="login()">Log in</button>
  </form>

</div>


<div class="signup-box" ng-if="tabArray.showSignup == true">

  <form class="signup-form" action="/users" method="post">
    <p style="font-size: 25px">Create an account</p>
    <hr>
    <div class="first-col">
      <p class="labels"><input type="text" name="user[email]" placeholder="email/login"></input></p>
      <p class="labels"><input type="password" name="user[password]" placeholder="password"></input></p>
      <p class="labels"><input type="password" name="user[password_confirmation]" placeholder="password confirmation"></input></p>
      <p class="labels"><input type="text" name="user[first_name]" placeholder="first name"></input></p>
      <p class="labels"><input type="text" name="user[last_name]" placeholder="last name"></input></p>
    </div>
    <div class="second-col">
      <p class="labels"><input type="text" name="user[age]" placeholder="age"></input></p>
      <p class="labels"><input style="height: 100px" name="user[description]" type="text" placeholder="about you"></input></p>
      <p class="labels"><input type="file" name="user[photo]" ng-change="previewFile()" placeholder="Upload photo"><br>
      <img src="" height="200" alt="Image preview..."></p>

      <button class="btn-success" ng-click="login()">Sign up</button>
    </div>
  </form>

</div>

<div class="profile-box" ng-if="tabArray.showProfile == true">
  <div class="profile-wrapper">
  <div class="profile-top">
    Johnny B. Goode
  </div>

  <div class="profile-main">
    <div class="pm-left">
      <div class="content-header">Personal Info:</div>
        <span class="user-label">nickname:</span> Jon <br>
        <span class="user-label">member since: </span> 2016 <br>
        <span class="user-label">age: </span> 27 <br>
        <span class="user-label">description: </span> blablablab <br>
    </div> <!-- pm-left -->

    <div class="pm-center">
      <div class="user-photo"></div>
      <div class="message-link">
        <button class="btn-success" ng-click="sendMessage()">Send a message</button>
      </div>
    </div> <!-- pm-center -->

    <div class="pm-right">
      <div class="player-info">
        <div class="content-header">Player Info:</div>
          <span class="user-label">games played: </span> 9 <br>
          <span class="user-label">games won: </span> 4 <br>
          <span class="user-label">best score: </span> 8-1 <br>
      </div><!-- player-info -->
      <div class="play-buttons">
        <div class="looking-to-play" ng-show="lookingToPlay = true">Looking to Play</div>
        <div class="not-looking-to-play" ng-show="lookingToPlay = false">Not Looking to Play</div>
      </div><!-- play-buttons -->
    </div><!-- pm-right -->

  </div><!-- profile-main -->
  </div><!-- profile-wrapper -->

</div><!-- profile-box -->


<%= yield %>

<footer ng-class="{ 'lower-footer': lower}">
    Copyright 2016
</footer>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script> -->
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC5TZNWeG6UJI4Gw8fTsaaHkd3rV7Qy5p8&callback=initMap">
</script>

</main><!--body-inner-wrap-->
</body>
</html>

app/views/users/show.html.erb
<div class="user-show" ng-init="activateFooter()">
	<div class="user-title">Inside user show page</div>

  <div class="profile-wrapper">
  <div class="profile-top">
    Johnny B. Goode
  </div>

  <div class="profile-main">
    <div class="pm-left">
      <div class="content-header">Personal Info:</div>
        <span class="user-label">nickname:</span> Jon <br>
        <span class="user-label">member since: </span> 2016 <br>
        <span class="user-label">age: </span> 27 <br>
        <span class="user-label">description: </span> blablablab <br>
    </div> <!-- pm-left -->

    <div class="pm-center">
      <div class="user-photo"></div>
      <div class="message-link">
        <button class="btn-success" ng-click="sendMessage()">Send a message</button>
      </div>
    </div> <!-- pm-center -->

    <div class="pm-right">
      <div class="player-info">
        <div class="content-header">Player Info:</div>
          <span class="user-label">games played: </span> 9 <br>
          <span class="user-label">games won: </span> 4 <br>
          <span class="user-label">best score: </span> 8-1 <br>
      </div><!-- player-info -->
      <div class="play-buttons">
        <div class="looking-to-play" ng-show="lookingToPlay = true">Looking to Play</div>
        <div class="not-looking-to-play" ng-show="lookingToPlay = false">Not Looking to Play</div>
      </div><!-- play-buttons -->
    </div><!-- pm-right -->

  </div><!-- profile-main -->
  </div><!-- profile-wrapper -->

</div><!-- profile-box -->
</div>